In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression ,LinearRegression ,Lasso ,Ridge
from sklearn.ensemble import RandomForestClassifier ,BaggingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split ,KFold ,cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.naive_bayes import GaussianNB ,MultinomialNB
from sklearn.neighbors import KNeighborsClassifier

In [2]:
data= load_wine()


In [3]:
dir(data)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [4]:
data.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [5]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [6]:
input = pd.DataFrame(data.data)
input.columns= data.feature_names
input

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [7]:
target = pd.DataFrame(data.target)
target

0
0    0
1    0
2    0
3    0
4    0
..  ..
173  2
174  2
175  2
176  2
177  2

[178 rows x 1 columns]

In [8]:
input.isnull().sum().sum()

np.int64(0)

In [9]:
target.isnull().sum().sum()

np.int64(0)

In [10]:
data2=pd.read_csv("weather.csv")

In [11]:
data2

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW   
1       14.0     26.9       3.6          4.4       9.7         ENE   
2       13.7     23.4       3.6          5.8       3.3          NW   
3       13.3     15.5      39.8          7.2       9.1          NW   
4        7.6     16.1       2.8          5.6      10.6         SSE   
..       ...      ...       ...          ...       ...         ...   
361      9.0     30.7       0.0          7.6      12.1         NNW   
362      7.1     28.4       0.0         11.6      12.7           N   
363     12.5     19.9       0.0          8.4       5.3         ESE   
364     12.5     26.9       0.0          5.0       7.1          NW   
365     12.3     30.2       0.0          6.0      12.6          NW   

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0             30.0         SW         NW           6.0  ...           29   
1             39.0          E          W           4.0  ...           36   
2             85.0          N        NNE           6.0  ...           69   
3             54.0        WNW          W          30.0  ...           56   
4             50.0        SSE        ESE          20.0  ...           49   
..             ...        ...        ...           ...  ...          ...   
361           76.0        SSE         NW           7.0  ...           15   
362           48.0        NNW        NNW           2.0  ...           22   
363           43.0        ENE        ENE          11.0  ...           47   
364           46.0        SSW        WNW           6.0  ...           39   
365           78.0         NW        WNW          31.0  ...           13   

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0         1019.7       1015.0         7         7     14.4     23.6   
1         1012.4       1008.4         5         3     17.5     25.7   
2         1009.5       1007.2         8         7     15.4     20.2   
3         1005.5       1007.0         2         7     13.5     14.1   
4         1018.3       1018.5         7         7     11.1     15.4   
..           ...          ...       ...       ...      ...      ...   
361       1016.1       1010.8         1         3     20.4     30.0   
362       1020.0       1016.9         0         1     17.2     28.2   
363       1024.0       1022.8         3         2     14.5     18.3   
364       1021.0       1016.2         6         7     15.8     25.9   
365       1009.6       1009.2         1         1     23.8     28.6   

     RainToday  RISK_MM RainTomorrow  
0           No      3.6          Yes  
1          Yes      3.6          Yes  
2          Yes     39.8          Yes  
3          Yes      2.8          Yes  
4          Yes      0.0           No  
..         ...      ...          ...  
361         No      0.0           No  
362         No      0.0           No  
363         No      0.0           No  
364         No      0.0           No  
365         No      0.0           No  

[366 rows x 22 columns]

In [12]:
data2.isnull().sum().sum()

np.int64(47)

In [13]:
data2.isnull().sum()

MinTemp           0
MaxTemp           0
Rainfall          0
Evaporation       0
Sunshine          3
WindGustDir       3
WindGustSpeed     2
WindDir9am       31
WindDir3pm        1
WindSpeed9am      7
WindSpeed3pm      0
Humidity9am       0
Humidity3pm       0
Pressure9am       0
Pressure3pm       0
Cloud9am          0
Cloud3pm          0
Temp9am           0
Temp3pm           0
RainToday         0
RISK_MM           0
RainTomorrow      0
dtype: int64

In [14]:
data2.dtypes

MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm       int64
Humidity9am        int64
Humidity3pm        int64
Pressure9am      float64
Pressure3pm      float64
Cloud9am           int64
Cloud3pm           int64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM          float64
RainTomorrow      object
dtype: object

In [15]:
lben=LabelEncoder()

In [16]:
data2['WindGustDir']=lben.fit_transform(data2['WindGustDir'])

In [17]:
data2["WindDir9am"]=lben.fit_transform(data2["WindDir9am"])

In [18]:
data2["WindDir3pm"]=lben.fit_transform(data2["WindDir3pm"])

In [19]:
data2["RainTomorrow"]=lben.fit_transform(data2["RainTomorrow"])

In [20]:
data2["RainToday"]=lben.fit_transform(data2["RainToday"])

In [21]:
data2

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3            7   
1       14.0     26.9       3.6          4.4       9.7            1   
2       13.7     23.4       3.6          5.8       3.3            7   
3       13.3     15.5      39.8          7.2       9.1            7   
4        7.6     16.1       2.8          5.6      10.6           10   
..       ...      ...       ...          ...       ...          ...   
361      9.0     30.7       0.0          7.6      12.1            6   
362      7.1     28.4       0.0         11.6      12.7            3   
363     12.5     19.9       0.0          8.4       5.3            2   
364     12.5     26.9       0.0          5.0       7.1            7   
365     12.3     30.2       0.0          6.0      12.6            7   

     WindGustSpeed  WindDir9am  WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0             30.0          12           7           6.0  ...           29   
1             39.0           0          13           4.0  ...           36   
2             85.0           3           5           6.0  ...           69   
3             54.0          14          13          30.0  ...           56   
4             50.0          10           2          20.0  ...           49   
..             ...         ...         ...           ...  ...          ...   
361           76.0          10           7           7.0  ...           15   
362           48.0           6           6           2.0  ...           22   
363           43.0           1           1          11.0  ...           47   
364           46.0          11          14           6.0  ...           39   
365           78.0           7          14          31.0  ...           13   

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0         1019.7       1015.0         7         7     14.4     23.6   
1         1012.4       1008.4         5         3     17.5     25.7   
2         1009.5       1007.2         8         7     15.4     20.2   
3         1005.5       1007.0         2         7     13.5     14.1   
4         1018.3       1018.5         7         7     11.1     15.4   
..           ...          ...       ...       ...      ...      ...   
361       1016.1       1010.8         1         3     20.4     30.0   
362       1020.0       1016.9         0         1     17.2     28.2   
363       1024.0       1022.8         3         2     14.5     18.3   
364       1021.0       1016.2         6         7     15.8     25.9   
365       1009.6       1009.2         1         1     23.8     28.6   

     RainToday  RISK_MM  RainTomorrow  
0            0      3.6             1  
1            1      3.6             1  
2            1     39.8             1  
3            1      2.8             1  
4            1      0.0             0  
..         ...      ...           ...  
361          0      0.0             0  
362          0      0.0             0  
363          0      0.0             0  
364          0      0.0             0  
365          0      0.0             0  

[366 rows x 22 columns]

In [22]:
si=SimpleImputer(strategy='mean')

In [23]:
data2['Sunshine']=si.fit_transform(data2[['Sunshine']])

In [24]:
data2['WindGustSpeed']=si.fit_transform(data2[['WindGustSpeed']])

In [25]:
data2['WindSpeed9am']=si.fit_transform(data2[['WindSpeed9am']])

In [26]:
data2['WindSpeed9am']=si.fit_transform(data2[['WindSpeed9am']])

In [27]:
data2['WindGustDir']=si.fit_transform(data2[['WindGustDir']])

In [28]:
data2.isnull().sum().sum()

np.int64(0)

In [29]:
inputt=data2.drop(["RainTomorrow"],axis=1)

In [30]:
inputt

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          7.0   
1       14.0     26.9       3.6          4.4       9.7          1.0   
2       13.7     23.4       3.6          5.8       3.3          7.0   
3       13.3     15.5      39.8          7.2       9.1          7.0   
4        7.6     16.1       2.8          5.6      10.6         10.0   
..       ...      ...       ...          ...       ...          ...   
361      9.0     30.7       0.0          7.6      12.1          6.0   
362      7.1     28.4       0.0         11.6      12.7          3.0   
363     12.5     19.9       0.0          8.4       5.3          2.0   
364     12.5     26.9       0.0          5.0       7.1          7.0   
365     12.3     30.2       0.0          6.0      12.6          7.0   

     WindGustSpeed  WindDir9am  WindDir3pm  WindSpeed9am  ...  Humidity9am  \
0             30.0          12           7           6.0  ...           68   
1             39.0           0          13           4.0  ...           80   
2             85.0           3           5           6.0  ...           82   
3             54.0          14          13          30.0  ...           62   
4             50.0          10           2          20.0  ...           68   
..             ...         ...         ...           ...  ...          ...   
361           76.0          10           7           7.0  ...           38   
362           48.0           6           6           2.0  ...           45   
363           43.0           1           1          11.0  ...           63   
364           46.0          11          14           6.0  ...           69   
365           78.0           7          14          31.0  ...           43   

     Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0             29       1019.7       1015.0         7         7     14.4   
1             36       1012.4       1008.4         5         3     17.5   
2             69       1009.5       1007.2         8         7     15.4   
3             56       1005.5       1007.0         2         7     13.5   
4             49       1018.3       1018.5         7         7     11.1   
..           ...          ...          ...       ...       ...      ...   
361           15       1016.1       1010.8         1         3     20.4   
362           22       1020.0       1016.9         0         1     17.2   
363           47       1024.0       1022.8         3         2     14.5   
364           39       1021.0       1016.2         6         7     15.8   
365           13       1009.6       1009.2         1         1     23.8   

     Temp3pm  RainToday  RISK_MM  
0       23.6          0      3.6  
1       25.7          1      3.6  
2       20.2          1     39.8  
3       14.1          1      2.8  
4       15.4          1      0.0  
..       ...        ...      ...  
361     30.0          0      0.0  
362     28.2          0      0.0  
363     18.3          0      0.0  
364     25.9          0      0.0  
365     28.6          0      0.0  

[366 rows x 21 columns]

In [31]:
targett=pd.DataFrame()

In [32]:
targett['RainToday']=data2['RainToday']

In [33]:
targett

RainToday
0            0
1            1
2            1
3            1
4            1
..         ...
361          0
362          0
363          0
364          0
365          0

[366 rows x 1 columns]

In [34]:
dt=cross_val_score(DecisionTreeClassifier(),inputt,targett,cv=7)
dt

array([1., 1., 1., 1., 1., 1., 1.])

In [35]:
rm=dt=cross_val_score(RandomForestClassifier(n_estimators=10),inputt,targett,cv=7)
rm

D:\anaconda\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
D:\anaconda\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimato

array([1., 1., 1., 1., 1., 1., 1.])

In [36]:
log=cross_val_score(LogisticRegression(max_iter=100000),inputt,targett,cv=7)
log

D:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y,

array([0.98113208, 1.        , 1.        , 1.        , 0.98076923,
       0.94230769, 1.        ])

In [37]:
svm=cross_val_score(SVC(),inputt,targett,cv=7)
svm

D:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y,

array([0.81132075, 0.81132075, 0.82692308, 0.82692308, 0.82692308,
       0.82692308, 0.80769231])

In [38]:
gn=cross_val_score(GaussianNB(),inputt,targett,cv=7)
gn

D:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y,

array([1., 1., 1., 1., 1., 1., 1.])

In [39]:
knn=cross_val_score(KNeighborsClassifier(n_neighbors=5),inputt,targett,cv=7)
knn

D:\anaconda\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
D:\anaconda\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
D:\anaconda\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
D:\anaconda\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fi

array([0.81132075, 0.9245283 , 0.90384615, 0.90384615, 0.80769231,
       0.76923077, 0.86538462])

In [40]:
print("Bagging with Logistic Regression:")
bagging_model = BaggingClassifier(
    estimator=make_pipeline(StandardScaler(), LogisticRegression(max_iter=5000)),
    n_estimators=100,
    random_state=42
)

#cross-validation
bag = cross_val_score(bagging_model, inputt, targett.values.ravel(), cv=7)

print(bag)


Bagging with Logistic Regression:
[1. 1. 1. 1. 1. 1. 1.]
